version: "3"

services:
  api:
    build: .
    image: nodeauth
    container_name: nodeauth
    command: yarn start
    ports:
      - "3333:3333"
    volumes:
      - ./:/home/node/app/
    depends_on:
      - migration
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nodeauth
    ports:
      - "5433:5432"

  migration:
    build: .
    image: migration
    command: yarn sequelize db:migrate
    depends_on:
      - postgres
